version: 2.1

jobs:
  install-all-dependency:
    machine:
      image: ubuntu-2204:2022.10.01
    steps:
      - checkout
      - run: npm i
  install-prod-dependency:
    machine:
      image: ubuntu-2204:2022.10.01
    steps:
      - checkout
      - run: npm i --omit-dev
  test:
    machine:
      image: ubuntu-2204:2022.10.01
    steps:
      - checkout
      - run: npm test
  build:
    machine:
      image: ubuntu-2204:2022.10.01
    steps:
      - checkout
      - run: npm run build

workflows:
  install-and-test:
    jobs:
      - install-all-dependency
      - test
